server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-details-service
          uri: lb://user-details-service
          predicates:
            - Path=/user-details-service/**
          filters:
            - AuthenticationFilter

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/security-service/**